version: '3'
services:
  ng-ssr-app:
    build: .
    ports:
      - "4000:4000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro  # Add the ':ro' flag to make the volume read-only
    depends_on:
      - ng-ssr-app