version: '3'
services:
  ng-ssr-app:
    build: .
    ports:
      - "4000:4000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ng-ssr-app